---
spring:
  profiles: auth
auth:
  security:
    passwordStrength: 10
    tokenSigningKey: 0WCuxOVrMJjUGhC6cR4GBLC9OhvL1YDNp96tUOdfCOKlhaO0C620YDadU4UfGdtt5IYjTJYPpNRMbQID5UEx1g1qg3igMijreTeV2CVRiN

---
spring:
  profiles: mybatis
  datasource:
    dynamic:
      primary: eth #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:p6spy:mysql://${MARIADB_DATABASE_MASTER_HOST:database-banksea-prod-1.cluster-cafmukmhaxmq.ap-southeast-1.rds.amazonaws.com}:${MARIADB_DATABASE_PORT:3306}/banksea?useUnicode=true&characterEncoding=utf-8&useMysqlMetadata=true&socketTimeout=60000&connectTimeout=30000&serverTimezone=UTC
          username: ${MARIADB_DATABASE_USERNAME:admin}
          password: ${MARIADB_DATABASE_PASSWORD:FvfyzhVM0LdUBoMFcJF9}
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        clickhouse:
          url: jdbc:clickhouse://${CK_HOST:54.179.236.140}:${CK_PORT:8123}
          username: ${CK_USERNAME:crawler}
          password: ${CK_PASSWORD:66WjtIK3}
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
        eth:
          url: jdbc:p6spy:mysql://${MARIADB_DATABASE_MASTER_HOST:database-banksea-prod-1.cluster-cafmukmhaxmq.ap-southeast-1.rds.amazonaws.com}:${MARIADB_DATABASE_PORT:3306}/ethereum_crawler?useUnicode=true&characterEncoding=utf-8&useMysqlMetadata=true&socketTimeout=60000&connectTimeout=30000&serverTimezone=UTC
          username: ${MARIADB_DATABASE_USERNAME:admin}
          password: ${MARIADB_DATABASE_PASSWORD:FvfyzhVM0LdUBoMFcJF9}
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        dev-clickhouse:
          url: jdbc:clickhouse://13.229.56.143:8123
          username: default
          password: Ptaaft3Q
          driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    hikari:
      read-only: false
      connection-test-query: SELECT 1
      connection-timeout: 80000
      maximum-pool-size: 20  # 最大连接数
      minimum-idle: 3   # 连接池空闲连接的最小数量
      idle-timeout: 60000 # 1min最长空闲时间
      validation-timeout: 3000
      login-timeout: 5
      max-lifetime: 60000 # 1min最大生存期  => 默认30min,怀疑被中间docker等关闭连接导致连接不可用，改小到1min
      data-source-properties: # see https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
        cachePrepStmts: true        # 是否自定义配置，为true时下面两个参数才生效
        prepStmtCacheSize: 250      # 连接池大小默认25，官方推荐250-500
        prepStmtCacheSqlLimit: 2048 # 单条语句最大长度默认256，官方推荐2048
        useServerPrepStmts: true    # 服务端启用预编译机制，客户端(jdbc driver)只要不close掉statement，该statement可以多次重复使用，而不用再执行prepareStatement
        useLocalSessionState: true
        rewriteBatchedStatements: true  # mysql自身实现的批量操作方法(转换成muti value的方式)，性能是最好的，因为它是一次io，一次解析执行，由于此时占位符个数应该是不定的，不建议使用服务端预编译机制，更不建议客户端缓存，需要注意一次批量的包大小。
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

mybatis-plus:
  #    mapper-locations: classpath:**/mapping/*.xml
  global-config:
    db-config:
      id-type: id_worker
  configuration:
    map-underscore-to-camel-case: true    #驼峰下划线转换
    cache-enabled: true
    lazyLoadingEnabled: true
    multipleResultSetsEnabled: true
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
